token = ""
channel_id = 1111111111111111
slash_roll_channel = 1111111111111111
slash_kl_channel = 1111111111111111
wish_channel = 1111111111111111
wr_channel = 1111111111111111
owner_id = 1111111111111111
mudae_id = 1111111111111111
prefix = "$"
roll_type = "wa"
max_k = [
    "$bronze 2",
    "$silver 2",
    "$gold 2",
    "$ruby 4",
    "$gold 4",
    "$Sapphire 4",
    "$Emerald 4",
    "$silver  4",
    "$bronze 4",
]

[sl]
Soulmate_message = ["SOULMATE", "chaoskey"]
no_rolls_left = [
    "the roulette is limited to",
    "A kakera command is being processed"
]

[kl]
no_kakera = ["You need an additional"]
givescrap_confirmation = "do you really want to give"
givescrap_error = [
    "Command RESTRICTED to the following roles",
    "Command restricted to admins",
    "This server doesn't have kakera scraps!",
    "Prerequisites: Sapphire",
]
kl_confirmation = [
    "Do you want to spend **50000**",
    "A command is already awaiting an answer!"
]
too_many_pins = ["you have too many pins"]
no_pins = [
    "No mudapins found!",
    "No pins were released!"
]
